language: csharp
solution: Automation.Web.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Automation.Web.sln
after_script:
  - nunit-console Automation.Web.dll